/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./components/layout/Aside.vue')['default']
    Bar: typeof import('./components/echarts/Bar.vue')['default']
    CommonEcharts: typeof import('./components/echarts/CommonEcharts.vue')['default']
    Header: typeof import('./components/layout/Header.vue')['default']
    Line: typeof import('./components/echarts/Line.vue')['default']
    MenuList: typeof import('./components/layout/MenuList.vue')['default']
    Pie: typeof import('./components/echarts/Pie.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenLeftOne: typeof import('./components/screen/screenLeftOne.vue')['default']
    ScreenLeftTwo: typeof import('./components/screen/screenLeftTwo.vue')['default']
    ScreenPie: typeof import('./components/screen/screenPie.vue')['default']
    ScreenRightTwo: typeof import('./components/screen/screenRightTwo.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon.vue')['default']
  }
}
