/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AirplaneComponent: typeof import('./src/components/selectComponent/selectInvoicePicker/components/airplaneComponent.vue')['default']
    ApplicationIcon: typeof import('./src/components/applicationIcon/index.vue')['default']
    ApplyCard: typeof import('./src/components/selectComponent/selectApplyPicker/components/applyCard.vue')['default']
    ApprovalStatus: typeof import('./src/components/approvalStatus/index.vue')['default']
    ConstInformationSelectionPage: typeof import('./src/components/ConstInformationSelectionPage.vue')['default']
    CostCenterCard: typeof import('./src/components/selectComponent/selectCostCenterPicker/components/costCenterCard.vue')['default']
    Dialog: typeof import('./src/components/dialog.vue')['default']
    InvoiceComponent: typeof import('./src/components/selectComponent/selectInvoicePicker/components/invoiceComponent.vue')['default']
    Loading: typeof import('./src/components/loading/index.vue')['default']
    LoanCard: typeof import('./src/components/selectComponent/selectLoanPicker/components/loanCard.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectApplyPicker: typeof import('./src/components/selectComponent/selectApplyPicker/index.vue')['default']
    SelectCityPicker: typeof import('./src/components/selectComponent/selectCityPicker/index.vue')['default']
    SelectCopyPeoplePicker: typeof import('./src/components/selectComponent/selectCopyPeoplePicker/index.vue')['default']
    SelectCostCenterPicker: typeof import('./src/components/selectComponent/selectCostCenterPicker/index.vue')['default']
    SelectCostPicker: typeof import('./src/components/selectComponent/selectCostPicker/index.vue')['default']
    SelectInvoicePicker: typeof import('./src/components/selectComponent/selectInvoicePicker/index.vue')['default']
    SelectLoanPicker: typeof import('./src/components/selectComponent/selectLoanPicker/index.vue')['default']
    SelectPeoplePicker: typeof import('./src/components/selectComponent/selectPeoplePicker/index.vue')['default']
    SelectPersonPicker: typeof import('./src/components/selectComponent/selectPersonPicker/index.vue')['default']
    TrainComponent: typeof import('./src/components/selectComponent/selectInvoicePicker/components/trainComponent.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCol: typeof import('vant/es')['Col']
    VanDialog: typeof import('vant/es')['Dialog']
    VanDivider: typeof import('vant/es')['Divider']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanRow: typeof import('vant/es')['Row']
    VanSticky: typeof import('vant/es')['Sticky']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
