export const applyType = [
    {'text': '差旅申请', 'value': 'travel', 'icon': 'icon_01.png', 'approveId': 'FK_CL_SQ'},
    {'text': '请假申请', 'value': 'leave', 'icon': 'application_icon_01.png', 'approveId': 'FK_QJ_SQ'},
// {'text': '借款申请', 'value': 'loanApprove', 'icon': 'application_icon_14.png', 'approveId': ''},
    {'text': '加班申请', 'value': 'work', 'icon': 'application_icon_02.png', 'approveId': 'FK_JB_SQ'},
    {'text': '费用申请', 'value': 'reimbursement', 'icon': 'application_icon_14.png', 'approveId': ''},
    {'text': '用章申请', 'value': 'seal', 'icon': 'application_icon_07.png', 'approveId': 'FK_GZ_SQ'},
    {'text': '用车申请', 'value': 'car', 'icon': 'cost_icon_01.png', 'approveId': 'FK_YC_SQ'},
// {'text': '物流', 'value': 'log', 'icon': 'application_icon_01.png', 'approveId': ''},
    {'text': '物品申购', 'value': 'shop', 'icon': 'application_icon_06.png', 'approveId': ''},
    {'text': '董事签批', 'value': 'sign', 'icon': 'application_icon_01.png', 'approveId': 'FK_GDQP_SQ'},
    {'text': '考勤申请', 'value': 'card', 'icon': 'application_icon_04.png', 'approveId': 'FK_BK_SQ'},
    {'text': '物品领用', 'value': 'itemCollection', 'icon': 'application_icon_05.png', 'approveId': 'FK_WP_SQ'},
    {'text': '基金报销', 'value': 'fund', 'icon': 'application_icon_01.png', 'approveId': 'FK_JJBX_SQ'},
// {'text': '订餐申请', 'value': 'ordering', 'icon': 'application_icon_01.png', 'approveId': ''},
    {'text': '培训申请', 'value': 'train', 'icon': 'application_icon_01.png', 'approveId': ''},
    {'text': '客户宴请', 'value': 'entertain', 'icon': 'application_icon_01.png', 'approveId': 'FK_KHYQ_SQ'},
    {'text': '会议记录', 'value': 'meeting', 'icon': 'application_icon_01.png', 'approveId': 'FK_HYJL_SQ'},
    {'text': '外出办公', 'value': 'outWork', 'icon': 'application_icon_03.png', 'approveId': 'FK_WCBG_SQ'},
// {'text': '合同申请', 'value': 'contract', 'icon': 'application_icon_01.png', 'approveId': ''},
    {'text': '快递物流', 'value': 'log', 'icon': 'application_icon_05.png', 'approveId': 'FK_WL_SQ'},
    {'text': '日常报销', 'value': 'rcbx', 'icon': 'application_icon_11.png', 'approveId': ''},
    {'text': '借款申请', 'value': 'jksq', 'icon': 'application_icon_13.png', 'approveId': ''},
    {'text': '差旅补助', 'value': 'clbx', 'icon': 'application_icon_12.png', 'approveId': ''},
    {'text': '其他申请', 'value': 'other', 'icon': 'application_icon_12.png', 'approveId': ''},
]
