/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AirplaneComponent: typeof import('./src/components/selectComponent/selectInvoicePicker/components/airplaneComponent.vue')['default']
    ApplicationIcon: typeof import('./src/components/applicationIcon/index.vue')['default']
    ApplyCard: typeof import('./src/components/selectComponent/selectApplyPicker/components/applyCard.vue')['default']
    ApprovalStatus: typeof import('./src/components/approvalStatus/index.vue')['default']
    ConstInformationSelectionPage: typeof import('./src/components/ConstInformationSelectionPage.vue')['default']
    CostCenterCard: typeof import('./src/components/selectComponent/selectCostCenterPicker/components/costCenterCard.vue')['default']
    Dialog: typeof import('./src/components/dialog.vue')['default']
    InvoiceComponent: typeof import('./src/components/selectComponent/selectInvoicePicker/components/invoiceComponent.vue')['default']
    Loading: typeof import('./src/components/loading/index.vue')['default']
    LoanCard: typeof import('./src/components/selectComponent/selectLoanPicker/components/loanCard.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectApplyPicker: typeof import('./src/components/selectComponent/selectApplyPicker/index.vue')['default']
    SelectCityPicker: typeof import('./src/components/selectComponent/selectCityPicker/index.vue')['default']
    SelectCopyPeoplePicker: typeof import('./src/components/selectComponent/selectCopyPeoplePicker/index.vue')['default']
    SelectCostCenterPicker: typeof import('./src/components/selectComponent/selectCostCenterPicker/index.vue')['default']
    SelectCostPicker: typeof import('./src/components/selectComponent/selectCostPicker/index.vue')['default']
    SelectInvoicePicker: typeof import('./src/components/selectComponent/selectInvoicePicker/index.vue')['default']
    SelectLoanPicker: typeof import('./src/components/selectComponent/selectLoanPicker/index.vue')['default']
    SelectPeoplePicker: typeof import('./src/components/selectComponent/selectPeoplePicker/index.vue')['default']
    SelectPersonPicker: typeof import('./src/components/selectComponent/selectPersonPicker/index.vue')['default']
    TrainComponent: typeof import('./src/components/selectComponent/selectInvoicePicker/components/trainComponent.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCol: typeof import('vant/es')['Col']
    VanDivider: typeof import('vant/es')['Divider']
    VanField: typeof import('vant/es')['Field']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanRow: typeof import('vant/es')['Row']
    VanSearch: typeof import('vant/es')['Search']
    VanSticky: typeof import('vant/es')['Sticky']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
