version: '3.8'
services:
  my_pilot_container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_pilot_container
    image: my_pilot_image
    ports:
      - "8080:8080"
#    environment:
#      - NODE_ENV=production
#      - DB_HOST=db
    depends_on:
      - pilot_rabbitmq
    networks:
      - my_pilot_network

  pilot_rabbitmq:
    image: rabbitmq:3-management
    container_name: pilot_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
#    volumes:
#      - mongo-data:/data/db
    networks:
      - my_pilot_network

networks:
  my_pilot_network:
    name: my_pilot_network  # 直接指定网络名，不会添加项目前缀
    driver: bridge
